USE instagram;

CREATE TABLE USERS ( USER_ID INT PRIMARY KEY, USER_NAME VARCHAR(30));

CREATE TABLE POSTS (POST_ID INT PRIMARY KEY, 
POST_TEXT VARCHAR(200), 
USER_ID INT, 
FOREIGN KEY(USER_ID) REFERENCES USERS (USER_ID));

CREATE TABLE LIKES (
LIKES_ID INT,
POST_ID INT, 
USER_ID INT, 
PRIMARY KEY (LIKES_ID, USER_ID), 
FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID), 
FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID));

CREATE TABLE COMMENTS ( COMMENT_ID INT PRIMARY KEY,
COMMENT_TEXT VARCHAR(500),
POST_ID INT,
USER_ID INT,
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID));