USE instagram;

INSERT INTO USERS VALUES 
	(1, "FAWWAZ"), (2, "BIBHU"), (3,"ANKUSH");

INSERT INTO POSTS VALUES 
	(1, "HELLO GUYS, WELCOME TO INSTAGRAM", 3),
	(2, "LADIES AND GENTLEMEN",2),
	(3, "WELCOME TO SAUDI ARABIA",1);

INSERT INTO LIKES VALUES
	(10 , 1, 3),
	(11 , 2 ,2),
	(12 , 3, 1);

INSERT INTO COMMENTS VALUES 
	(20, "NICE POST", 1, 3),
	(21, "AWESOME", 2, 2),
	(22, "LOOKING FAB", 3, 1);